name: sealed-fun
description: >-
  TBD
version: 1.0.0
homepage: https://github.com/diegopacheco/dart-playground/tree/main/pocs/sealed-fun
documentation: https://github.com/diegopacheco/dart-playground/blob/main/pocs/sealed-fun/README.md

environment:
  sdk: '>=2.12.0 <3.0.0'
  
#dependencies:

dev_dependencies:
  test: '>=1.24.5 <2.0.0'
